### ISSUE TITLE
import sky  - Anaconda No module named 'sky.view'; 'sky' is not a package 

### ISSUE THREAD

**Issue by MindaugasVaitkus2** [kootenpv/sky#10]
Anaconda distribution in python 3 does not find module sky. How to fix it?

(py36) C:\Users\User\Anaconda3\envs\py36\Lib\site-packages\sky>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sky
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Anaconda3\envs\py36\Lib\site-packages\sky\sky.py", line 5, in <module>
    from sky.view import view
ModuleNotFoundError: No module named 'sky.view'; 'sky' is not a package

**Comment by kootenpv** [comment]
Please try again, should be fixed as of `0.0.201`

**Comment by MindaugasVaitkus2** [comment]
I successfully installed version 0.0.201 using pip3 install -U sky

Installing collected packages: sky
  Found existing installation: sky 0.0.199
    Uninstalling sky-0.0.199:
      Successfully uninstalled sky-0.0.199
Successfully installed sky-0.0.201

**Comment by MindaugasVaitkus2** [comment]
I get new error. 1) Use `pip3 install ZODB zodbpickle` to install, or use a different backend. 2) After I install ModuleNotFoundError: No module named 'sky.view'; 'sky' is not a package.

(py36) C:\Users\User\Desktop\Documents\GitHub\sky>from sky.crawler_plugins import CrawlFilePluginNews
'from' is not recognized as an internal or external command,
operable program or batch file.

(py36) C:\Users\User\Desktop\Documents\GitHub\sky>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sky
>>> from sky.crawler_services import CrawlFileService
ZODB not properly installed and cannot be used as data backend.
Use `pip3 install ZODB zodbpickle` to install, or use a different backend.
>>> from sky.crawler_plugins import CrawlFilePluginNews
Optional ZODB not possible as backend. Use `pip3 install ZODB zodbpickle`

After  ZODB zodbpickle installation. 

(py36) C:\Users\User\Desktop\Documents\GitHub\sky\sky>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sky
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Desktop\Documents\GitHub\sky\sky\sky.py", line 5, in <module>
    from sky.view import view
ModuleNotFoundError: No module named 'sky.view'; 'sky' is not a package
>>> from sky.crawler_services import CrawlFileService
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Desktop\Documents\GitHub\sky\sky\sky.py", line 5, in <module>
    from sky.view import view
ModuleNotFoundError: No module named 'sky.view'; 'sky' is not a package
>>> from sky.crawler_plugins import CrawlFilePluginNews
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Desktop\Documents\GitHub\sky\sky\sky.py", line 5, in <module>
    from sky.view import view
ModuleNotFoundError: No module named 'sky.view'; 'sky' is not a package
