### ISSUE TITLE
After clean install  there appears to be a missing file

### ISSUE THREAD

**Issue by redevries** [kootenpv/sky#8]
I'm pretty much a python noob, but I'd like to take a look at Sky. So, I tried a clean install from the updated package, but when I enter 'sky view' this is what I get. Any guidance appreciated :)

```
(myenv) REs-MacBook-Pro:~ redevries$ sky view
Traceback (most recent call last):
  File "/Users/redevries/.virtualenvs/myenv/bin/sky", line 7, in <module>
    from sky.sky import main
  File "/Users/redevries/.virtualenvs/myenv/lib/python3.6/site-packages/sky/sky.py", line 5, in <module>
    from sky.view import view
  File "/Users/redevries/.virtualenvs/myenv/lib/python3.6/site-packages/sky/view/view.py", line 11, in <module>
    from sky.crawler import crawl
  File "/Users/redevries/.virtualenvs/myenv/lib/python3.6/site-packages/sky/crawler/crawl.py", line 10, in <module>
    from sky.crawler.crawling import Crawler
  File "/Users/redevries/.virtualenvs/myenv/lib/python3.6/site-packages/sky/crawler/crawling.py", line 21, in <module>
    from sky.scraper import Scraper
  File "/Users/redevries/.virtualenvs/myenv/lib/python3.6/site-packages/sky/scraper.py", line 29, in <module>
    from sky.get_date import get_dates
  File "/Users/redevries/.virtualenvs/myenv/lib/python3.6/site-packages/sky/get_date.py", line 35, in <module>
    with open(fname, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/redevries/.virtualenvs/myenv/lib/python3.6/site-packages/sky/data/date_translation_table.json'
(myenv) REs-MacBook-Pro:~ redevries$ 
```

**Comment by redevries** [comment]
Never mind, just downloaded missing files from /view and /sky. Problem solved.
