### ISSUE TITLE
json.decoder.JSONDecodeError: while testing sky installation

### ISSUE THREAD

**Issue by MindaugasVaitkus2** [kootenpv/sky#9]
I cannot figure out how to solve the error below:

(py36) C:\Users\User\Anaconda3\envs\py36\Lib\site-packages\sky\crawler>python test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    import crawling
  File "C:\Users\User\Anaconda3\envs\py36\Lib\site-packages\sky\crawler\crawling.py", line 21, in <module>
    from sky.scraper import Scraper
  File "C:\Users\User\Anaconda3\envs\py36\lib\site-packages\sky\scraper.py", line 29, in <module>
    from sky.get_date import get_dates
  File "C:\Users\User\Anaconda3\envs\py36\lib\site-packages\sky\get_date.py", line 36, in <module>
    date_translation_table = json.load(f)
  File "C:\Users\User\Anaconda3\envs\py36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\User\Anaconda3\envs\py36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\Anaconda3\envs\py36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\Anaconda3\envs\py36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kootenpv** [comment]
Please try again, should be fixed as of `0.0.201`
